import 'package:flutter/material.dart';

import '../models/recipe.dart';

/// Reusable, scrollable rendering of a [Recipe]. Used by the AI output screen
/// and the saved-recipe detail view.
class RecipeView extends StatelessWidget {
  const RecipeView({super.key, required this.recipe, this.padding});

  final Recipe recipe;
  final EdgeInsetsGeometry? padding;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    if (recipe.isInsufficient) {
      return ListView(
        padding: padding ?? const EdgeInsets.all(16),
        children: [
          const SizedBox(height: 24),
          Icon(Icons.info_outline,
              size: 48, color: theme.colorScheme.secondary),
          const SizedBox(height: 12),
          Text(
            'Insufficient ingredients',
            textAlign: TextAlign.center,
            style: theme.textTheme.titleLarge
                ?.copyWith(fontWeight: FontWeight.w700),
          ),
          const SizedBox(height: 12),
          _Card(
            child: Text(recipe.safetyNotes),
          ),
        ],
      );
    }

    return ListView(
      padding: padding ?? const EdgeInsets.all(16),
      children: [
        Text(
          recipe.title,
          style: theme.textTheme.headlineSmall
              ?.copyWith(fontWeight: FontWeight.w800),
        ),
        const SizedBox(height: 12),
        Row(
          children: [
            _MetaPill(
              icon: Icons.schedule,
              label: '${recipe.cookTimeMin} min',
            ),
            const SizedBox(width: 8),
            _MetaPill(
              icon: Icons.local_fire_department_outlined,
              label: recipe.difficulty,
            ),
          ],
        ),
        const SizedBox(height: 20),

        _Section(
          icon: Icons.check_circle_outline,
          title: 'Ingredients used',
          child: _BulletList(items: recipe.ingredientsUsed),
        ),

        if (recipe.missingOptional.isNotEmpty)
          _Section(
            icon: Icons.add_shopping_cart_outlined,
            title: 'Optional / missing',
            child: _BulletList(
              items: recipe.missingOptional,
              color: theme.colorScheme.secondary,
            ),
          ),

        _Section(
          icon: Icons.format_list_numbered,
          title: 'Steps',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              for (var i = 0; i < recipe.steps.length; i++)
                Padding(
                  padding: const EdgeInsets.only(bottom: 10),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      CircleAvatar(
                        radius: 13,
                        backgroundColor: theme.colorScheme.primary,
                        child: Text(
                          '${i + 1}',
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 12,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(child: Text(recipe.steps[i])),
                    ],
                  ),
                ),
            ],
          ),
        ),

        if (recipe.substitutions.isNotEmpty)
          _Section(
            icon: Icons.swap_horiz,
            title: 'Substitutions',
            child: _BulletList(items: recipe.substitutions),
          ),

        if (recipe.safetyNotes.isNotEmpty)
          _Section(
            icon: Icons.health_and_safety_outlined,
            title: 'Safety & allergen notes',
            highlight: true,
            child: Text(recipe.safetyNotes),
          ),

        const SizedBox(height: 8),
        Text(
          'Generated by AI — please double-check ingredients, allergens, and '
          'cooking temperatures before eating.',
          style: theme.textTheme.bodySmall
              ?.copyWith(color: Colors.grey.shade500),
        ),
      ],
    );
  }
}

class _Section extends StatelessWidget {
  const _Section({
    required this.icon,
    required this.title,
    required this.child,
    this.highlight = false,
  });

  final IconData icon;
  final String title;
  final Widget child;
  final bool highlight;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: _Card(
        color: highlight ? const Color(0xFFFFF3E0) : Colors.white,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, size: 20, color: theme.colorScheme.primary),
                const SizedBox(width: 8),
                Text(
                  title,
                  style: theme.textTheme.titleMedium
                      ?.copyWith(fontWeight: FontWeight.w700),
                ),
              ],
            ),
            const SizedBox(height: 10),
            child,
          ],
        ),
      ),
    );
  }
}

class _Card extends StatelessWidget {
  const _Card({required this.child, this.color});
  final Widget child;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: color ?? Colors.white,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: child,
    );
  }
}

class _BulletList extends StatelessWidget {
  const _BulletList({required this.items, this.color});
  final List<String> items;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        for (final item in items)
          Padding(
            padding: const EdgeInsets.only(bottom: 6),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Icon(Icons.circle, size: 7, color: color ?? Colors.grey),
                const SizedBox(width: 10),
                Expanded(child: Text(item)),
              ],
            ),
          ),
      ],
    );
  }
}

class _MetaPill extends StatelessWidget {
  const _MetaPill({required this.icon, required this.label});
  final IconData icon;
  final String label;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: theme.colorScheme.primary.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 16, color: theme.colorScheme.primary),
          const SizedBox(width: 6),
          Text(
            label,
            style: TextStyle(
              color: theme.colorScheme.primary,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }
}
