import 'package:flutter/material.dart';

import '../models/recipe.dart';

/// Reusable, scrollable rendering of a [Recipe]. Used by the AI output screen
/// and the saved-recipe detail view.
class RecipeView extends StatelessWidget {
  const RecipeView({
    super.key,
    required this.recipe,
    this.padding,
    this.isGeneratingImage = false,
  });

  final Recipe recipe;
  final EdgeInsetsGeometry? padding;

  /// When true, shows a "plating your dish" placeholder while the AI image
  /// is still being generated.
  final bool isGeneratingImage;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    if (recipe.isInsufficient) {
      return ListView(
        padding: padding ?? const EdgeInsets.all(16),
        children: [
          const SizedBox(height: 24),
          Icon(Icons.info_outline,
              size: 48, color: theme.colorScheme.secondary),
          const SizedBox(height: 12),
          Text(
            'Insufficient ingredients',
            textAlign: TextAlign.center,
            style: theme.textTheme.titleLarge
                ?.copyWith(fontWeight: FontWeight.w700),
          ),
          const SizedBox(height: 12),
          _Card(
            child: Text(recipe.safetyNotes),
          ),
        ],
      );
    }

    return ListView(
      padding: padding ?? const EdgeInsets.all(16),
      children: [
        if (recipe.hasImage || isGeneratingImage) ...[
          _HeroImage(
            recipe: recipe,
            isGenerating: isGeneratingImage && !recipe.hasImage,
          ),
          const SizedBox(height: 16),
        ],
        Text(
          recipe.title,
          style: theme.textTheme.headlineSmall
              ?.copyWith(fontWeight: FontWeight.w800),
        ),
        const SizedBox(height: 12),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: [
            _MetaPill(
              icon: Icons.schedule,
              label: '${recipe.cookTimeMin} min',
            ),
            _MetaPill(
              icon: Icons.local_fire_department_outlined,
              label: recipe.difficulty,
            ),
            if (recipe.servings > 0)
              _MetaPill(
                icon: Icons.people_alt_outlined,
                label: '${recipe.servings} '
                    'serving${recipe.servings == 1 ? '' : 's'}',
              ),
          ],
        ),
        const SizedBox(height: 20),

        if (recipe.hasNutrition) ...[
          _NutritionCard(recipe: recipe),
          const SizedBox(height: 16),
        ],

        _Section(
          icon: Icons.check_circle_outline,
          title: 'Ingredients used',
          child: _BulletList(items: recipe.ingredientsUsed),
        ),

        if (recipe.missingOptional.isNotEmpty)
          _Section(
            icon: Icons.add_shopping_cart_outlined,
            title: 'Optional / missing',
            child: _BulletList(
              items: recipe.missingOptional,
              color: theme.colorScheme.secondary,
            ),
          ),

        _Section(
          icon: Icons.format_list_numbered,
          title: 'Steps',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              for (var i = 0; i < recipe.steps.length; i++)
                Padding(
                  padding: const EdgeInsets.only(bottom: 10),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      CircleAvatar(
                        radius: 13,
                        backgroundColor: theme.colorScheme.primary,
                        child: Text(
                          '${i + 1}',
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 12,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(child: Text(recipe.steps[i])),
                    ],
                  ),
                ),
            ],
          ),
        ),

        if (recipe.substitutions.isNotEmpty)
          _Section(
            icon: Icons.swap_horiz,
            title: 'Substitutions',
            child: _BulletList(items: recipe.substitutions),
          ),

        if (recipe.safetyNotes.isNotEmpty)
          _Section(
            icon: Icons.health_and_safety_outlined,
            title: 'Safety & allergen notes',
            highlight: true,
            child: Text(recipe.safetyNotes),
          ),

        const SizedBox(height: 8),
        Text(
          'Generated by AI — please double-check ingredients, allergens, and '
          'cooking temperatures before eating.',
          style: theme.textTheme.bodySmall
              ?.copyWith(color: Colors.grey.shade500),
        ),
      ],
    );
  }
}

/// Large rounded hero image of the finished dish (or a loading placeholder
/// while the AI photo is still being generated).
class _HeroImage extends StatelessWidget {
  const _HeroImage({required this.recipe, required this.isGenerating});

  final Recipe recipe;
  final bool isGenerating;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    if (isGenerating) {
      return Container(
        height: 200,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(22),
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              theme.colorScheme.primary.withValues(alpha: 0.12),
              theme.colorScheme.secondary.withValues(alpha: 0.12),
            ],
          ),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const SizedBox(
              width: 28,
              height: 28,
              child: CircularProgressIndicator(strokeWidth: 3),
            ),
            const SizedBox(height: 12),
            Text(
              'Plating your dish…',
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.primary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
      );
    }

    return ClipRRect(
      borderRadius: BorderRadius.circular(22),
      child: Stack(
        children: [
          Image.memory(
            recipe.imageBytes!,
            height: 220,
            width: double.infinity,
            fit: BoxFit.cover,
            gaplessPlayback: true,
          ),
          Positioned.fill(
            child: DecoratedBox(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Colors.transparent,
                    Colors.black.withValues(alpha: 0.55),
                  ],
                ),
              ),
            ),
          ),
          Positioned(
            left: 16,
            right: 16,
            bottom: 14,
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 10, vertical: 5),
                  decoration: BoxDecoration(
                    color: Colors.white.withValues(alpha: 0.9),
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.auto_awesome,
                          size: 14, color: theme.colorScheme.primary),
                      const SizedBox(width: 4),
                      Text(
                        'AI photo',
                        style: theme.textTheme.labelSmall?.copyWith(
                          color: theme.colorScheme.primary,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _Section extends StatelessWidget {
  const _Section({
    required this.icon,
    required this.title,
    required this.child,
    this.highlight = false,
  });
  final IconData icon;
  final String title;
  final Widget child;
  final bool highlight;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: _Card(
        color: highlight ? const Color(0xFFFFF3E0) : Colors.white,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, size: 20, color: theme.colorScheme.primary),
                const SizedBox(width: 8),
                Text(
                  title,
                  style: theme.textTheme.titleMedium
                      ?.copyWith(fontWeight: FontWeight.w700),
                ),
              ],
            ),
            const SizedBox(height: 10),
            child,
          ],
        ),
      ),
    );
  }
}

class _Card extends StatelessWidget {
  const _Card({required this.child, this.color});
  final Widget child;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: color ?? Colors.white,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: child,
    );
  }
}

class _BulletList extends StatelessWidget {
  const _BulletList({required this.items, this.color});
  final List<String> items;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        for (final item in items)
          Padding(
            padding: const EdgeInsets.only(bottom: 6),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Icon(Icons.circle, size: 7, color: color ?? Colors.grey),
                const SizedBox(width: 10),
                Expanded(child: Text(item)),
              ],
            ),
          ),
      ],
    );
  }
}

class _MetaPill extends StatelessWidget {
  const _MetaPill({required this.icon, required this.label});
  final IconData icon;
  final String label;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: theme.colorScheme.primary.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 16, color: theme.colorScheme.primary),
          const SizedBox(width: 6),
          Text(
            label,
            style: TextStyle(
              color: theme.colorScheme.primary,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }
}

/// Visual nutrition panel: a calorie badge plus colored macro bars.
class _NutritionCard extends StatelessWidget {
  const _NutritionCard({required this.recipe});
  final Recipe recipe;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    // Approximate calories from each macro to size the bars proportionally.
    final proteinCals = recipe.proteinG * 4;
    final carbsCals = recipe.carbsG * 4;
    final fatCals = recipe.fatG * 9;
    final totalMacroCals =
        (proteinCals + carbsCals + fatCals).clamp(1, 1 << 31);

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20),
        gradient: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF2E7D32), Color(0xFF43A047)],
        ),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF2E7D32).withValues(alpha: 0.25),
            blurRadius: 14,
            offset: const Offset(0, 6),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.monitor_heart_outlined, color: Colors.white),
              const SizedBox(width: 8),
              Text(
                'Nutrition (per serving)',
                style: theme.textTheme.titleMedium?.copyWith(
                  color: Colors.white,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              // Calorie badge
              Container(
                width: 96,
                height: 96,
                decoration: BoxDecoration(
                  color: Colors.white.withValues(alpha: 0.15),
                  shape: BoxShape.circle,
                  border: Border.all(
                    color: Colors.white.withValues(alpha: 0.5),
                    width: 2,
                  ),
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      '${recipe.calories}',
                      style: theme.textTheme.headlineSmall?.copyWith(
                        color: Colors.white,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                    const Text(
                      'kcal',
                      style: TextStyle(color: Colors.white70, fontSize: 12),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 18),
              // Macro bars
              Expanded(
                child: Column(
                  children: [
                    _MacroBar(
                      label: 'Protein',
                      grams: recipe.proteinG,
                      fraction: proteinCals / totalMacroCals,
                      color: const Color(0xFFFFD54F),
                    ),
                    const SizedBox(height: 10),
                    _MacroBar(
                      label: 'Carbs',
                      grams: recipe.carbsG,
                      fraction: carbsCals / totalMacroCals,
                      color: const Color(0xFF81D4FA),
                    ),
                    const SizedBox(height: 10),
                    _MacroBar(
                      label: 'Fat',
                      grams: recipe.fatG,
                      fraction: fatCals / totalMacroCals,
                      color: const Color(0xFFFF8A65),
                    ),
                  ],
                ),
              ),
            ],
          ),
          if (recipe.fiberG > 0) ...[
            const SizedBox(height: 14),
            Row(
              children: [
                const Icon(Icons.grass, color: Colors.white70, size: 18),
                const SizedBox(width: 6),
                Text(
                  'Fiber: ${recipe.fiberG} g',
                  style: const TextStyle(color: Colors.white),
                ),
              ],
            ),
          ],
          if (recipe.nutritionNote.isNotEmpty) ...[
            const SizedBox(height: 14),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.white.withValues(alpha: 0.15),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Icon(Icons.lightbulb_outline,
                      color: Colors.white, size: 18),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      recipe.nutritionNote,
                      style: const TextStyle(color: Colors.white),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }
}

class _MacroBar extends StatelessWidget {
  const _MacroBar({
    required this.label,
    required this.grams,
    required this.fraction,
    required this.color,
  });

  final String label;
  final int grams;
  final double fraction;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              label,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 12,
                fontWeight: FontWeight.w600,
              ),
            ),
            Text(
              '$grams g',
              style: const TextStyle(
                color: Colors.white,
                fontSize: 12,
                fontWeight: FontWeight.w700,
              ),
            ),
          ],
        ),
        const SizedBox(height: 4),
        ClipRRect(
          borderRadius: BorderRadius.circular(6),
          child: LinearProgressIndicator(
            value: fraction.isFinite ? fraction.clamp(0.0, 1.0) : 0.0,
            minHeight: 8,
            backgroundColor: Colors.white.withValues(alpha: 0.2),
            valueColor: AlwaysStoppedAnimation<Color>(color),
          ),
        ),
      ],
    );
  }
}
